TRAIN:
  ENABLE: True
  DATASET: kinetics_sparse
  BATCH_SIZE: 2
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: pyav
  NUM_FRAMES: 32
  SAMPLING_RATE: 16
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  PATH_LABEL_SEPARATOR: " "
UNIFORMERV2:
  BACKBONE: 'uniformerv2_b16'
  N_LAYERS: 4
  N_DIM: 768
  N_HEAD: 12
  MLP_FACTOR: 4.0
  BACKBONE_DROP_PATH_RATE: 0.1
  DROP_PATH_RATE: 0.1
  MLP_DROPOUT: [0.5, 0.5, 0.5, 0.5]
  CLS_DROPOUT: 0.5
  RETURN_LIST: [8, 9, 10, 11]
  NO_LMHRA: True
  TEMPORAL_DOWNSAMPLE: False
MODEL:
  NUM_CLASSES: 2
  ARCH: uniformerv2
  MODEL_NAME: Uniformerv2
  LOSS_FUNC: focal_loss
  DROPOUT_RATE: 0.5
  USE_CHECKPOINT: True
TEST:
  ENABLE: True
  DATASET: kinetics_sparse
  BATCH_SIZE: 16
  NUM_SPATIAL_CROPS: 3
  NUM_ENSEMBLE_VIEWS: 4
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
SOLVER:
  BASE_LR: 1e-5
  WARMUP_EPOCHS: 5
  MAX_EPOCH: 2
  OPTIMIZING_METHOD: adamw
  WEIGHT_DECAY: 0.05
  MOMENTUM: 0.9
NUM_GPUS: 1
OUTPUT_DIR: ./output/custom_referral
